name: smart_tourist_safety_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  intl: ^0.20.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_translation: ^0.20.1
  flutter_gen: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true  # <- This must be properly indented under 'flutter'

flutter-gen:
  output: lib/gen/